language: php
dist: trusty
sudo: required
script: bash deploy/travis-build.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: mo@neva.li
before_install:
- openssl aes-256-cbc -K $encrypted_a2a6c6aaee56_key -iv $encrypted_a2a6c6aaee56_iv
  -in deploy/deploy.tar.enc -out deploy/deploy.tar -d
- tar xvf deploy/deploy.tar
- chmod 600 deploy/deploy_key
